name: Automated API tests using Newman CLI

on:
  push:
  schedule:
     - cron: '*/5 * * * *'  # Run every 5 minutes

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Install Newman CLI and the HTML reporter
      - name: Install Newman CLI and HTML reporter
        run: |
          npm install -g newman newman-reporter-html

      # Run the Postman collection with Newman and generate an HTML report
      - name: Run API tests
        id: run_tests
        run: |
          newman run "Platzi-fake store.postman_collection.json" --reporters cli,html --reporter-html-export report.html || exit 1

      # Debugging step to list files in the directory
      - name: List files for debugging
        run: ls -la

      # Send the HTML report via email
      #- name: Send Email with POSTMAN Report
        #uses: dawidd6/action-send-mail@v3
        #with:
          #server_address: smtp.gmail.com
          #server_port: 587
          #username: ${{ secrets.EMAIL }}
          #password: ${{ secrets.PASSWORD }}
          #subject: "Postman API Test Report"
          #to: orji.motopayng@gmail.com
          #from: ndubuisiaso@gmail.com
          #body: "Attached is the Postman API test report."
          #attachments: report.html